`defer` + `recover` позволяет перехватывать панику

```go
func main() {
    defer func() {
        if r := recover(); r != nil {
            fmt.Println("Recovered:", r)
        }
    }()
    panic("Oops!")
}
```
