#prog #prog/cpp

Анализ начинаем с того, что спрашиваем себя, что может генерировать исключения?
Затем рассуждаем про ресурсы, инварианты
Например:
- `std::logic_error` - конструктор исключения, их не генерирует
- `*value` - разыменовывание указателя, не генерирует, встроенный тип

1) Пробуем понять, что происходит в программе. Анализируем ресурсы: обращение к памяти, файлы, соединение с интернетом и т.д. Что может генерировать исключение?
2) Анализируем поведение функции, когда исключение возбуждается. Остались ли какие-то ресурсы в некорректном состоянии? Есть ли утечка ресурсов (не освобождаются за время выполнения функции)?
3) Определите, предоставляет ли функция какие-либо гарантии безопасности исключений. Например, некоторые функции могут гарантировать отсутствие утечек ресурсов или сохранение определенных структур данных в согласованном состоянии даже при наличии исключений. Категории безопасности относительно исключений  #/todo
4) Подумайте, как функция вызывается? Могут ли ее, например, вызвать много раз в одно и то же время, что приведет к некорректным результатам?
5) Попробовать затестить функцию на разных входных данных

Пример:

```c++
int* create_array(size_t size) {
  int* arr = new int[size];
  try {
    for (size_t i = 0; i < size; i++) {
      arr[i] = 0;
    }
  } catch (...) {
    delete[] arr; // Release allocated memory
    throw;        // Rethrow exception
  }
  return arr;
}
```

If `new` fails to allocate the requested memory and returns a `nullptr`, the `create_array` function throws a `std::bad_alloc` exception to indicate that the memory allocation has failed. Since no memory has been successfully allocated at this point, there is no need to free any memory.

On the other hand, if the memory allocation is successful, the function initializes the array and returns a pointer to it. If an exception is thrown after this point, the exception handling code releases the allocated memory using the `delete[]` operator to avoid leaking memory. By freeing the allocated memory immediately, the function ensures that no memory leaks occur even if an exception is thrown.

`==` может изменить `value`, если этот оператор перегружен и value передается по ссылке или указателю